baseURL: "https://annsopirate.github.io/"
languageCode: "en-us"
title: "Portfolio de Anne-Sophie Hovart"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: true

  favicon: "/images/icon.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  #customMenus:
    #- name: "Blog"
      #Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/moi.png"
  name: "Anne-Sophie Hovart"
  namecolor: ffc107
  profession: "Informatique, web design, UX/UI design, communication, photographie, infographie, ..."
  github: "https://github.com/annsopirate"
  #gitlab: "https://gitlab.com"
  linkedin: "https://www.linkedin.com/in/anne-sophie-hovart/"
  #twitter: "https://twitter.com/"
  #instagram: "https://instagram.com/"
  #facebook: "https://facebook.com"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "🌈 Heyyy ! Moi c’est Anne-Sophie, j’ai 23 ans et je suis en ce moment à la recherche d'un emploi dans l'informatique, le webdesign et l'UX/UI Design !"
  descripe_l2_person: "🎓 Récemment diplômée d’un Bac + 4 en UX/UI Design chez MyDigitalSchool, j'ai d'abord construit mes bases techniques avec un DUT Informatique, avant de me spécialiser en validant (avec mention bien) ma LP CréaWeb à l’IUT de Lens. Lors de mes études, j'ai pu forger mon expérience professionnelle à travers différents stages et alternances, tels que : \n- Alternances chez [Croquante](https://croquante.fr/) et [DC Digital](https://www.dc-digital.eu/) ; \n- Stages au Centre Hospitalier d'Hénin-Beaumont (pôle informatique) et chez [XavPC](https://xavpc.fr/)."
  descripe_l3_person: "🌟 Mes études et mes expériences m’ont permis de développer des compétences solides et d'apprendre de nombreuses choses diverses et variées. Voici ce qui me plaît par-dessus tout :"
  descripe_l4_person: "- l'UX/UI ; \n- Le maquettage et le prototypage (Figma) ; \n- La création de sites (Divi Builder, Elementor, WordPress) ; \n- Le rédactionnel (pour les réseaux sociaux et pour les sites internet) ; \n- Le référencement naturel (SEO) ; \n- La photographie (téléphone, numérique, hybride) ; \n- La création de vidéos pour des projets personnels ; \n- Le motion design (After Effects) ; \n- Le développement front-end."
  descripe_l5_person: "✨ Étant curieuse, j'ai profité d'être à la Mission Locale pour effectuer de nombreux stages, tel que celui chez [SurMesures](https://www.chezsurmesures.com/). Bien que ce soit hors du secteur informatique, cette immersion m’a permis de découvrir le milieu de l'entreprise à 360° (ses employés, ses urgences, sa clientèle) ainsi que le fonctionnement de ses 5 services clés : les pôles administratif, commerce, communication, production et atelier."
  descripe_l6_person: "🎨 À part ça, le dessin, la photographie, la lecture, l'écriture, le cinéma et les Rubik's Cube sont mes passe-temps favoris !"
  descripe_l7_person: "Tu veux voir les projets que j'ai réalisés ? clique [ici](#projects) !"
 
  


  skills:
    - name: Figma
      percentage: 65
    - name: XD
      percentage: 50
    - name: WordPress
      percentage: 70
    - name: Divi Builder
      percentage: 70
    - name: Lightroom Classic
      percentage: 70
    - name : After Effects (en cours d'acquisition)
      percentage: 40
    - name : Premiere Pro (en cours d'acquisition)
      percentage: 40
    - name : Photoshop (en cours d'acquisition)
      percentage : 30
    - name : Photographie
      percentage : 50
    - name: Markdown
      percentage: 95
    - name: HTML/CSS
      percentage: 80
    - name: SQL
      percentage: 80
    - name: Hugo
      percentage: 60
    - name: PHP
      percentage: 40
        

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "MBA Expert"
      branch: "UI/UX Design (Bac + 4)"
      university: "MyDigitalSchool"
      startedyear: "sept. 2024"
      graduation: "sept. 2025"
    - degree: "Licence Professionnelle"
      branch: "CréaWeb"
      university: "IUT de Lens"
      startedyear: "2022"
      graduation: "2023"
    - degree: "DUT"
      branch: "Informatique"
      university: "IUT de Lens"
      startedyear: "2020"
      graduation: "2022"
    - degree: "BAC S"
      branch: "Spé mathématiques"
      university: "Lycée Arthur Rimbaud"
      startedyear: "2019"
      graduation: "2020"

  # Projects
  projects:

    - name: "Photographies"
      date: "> 2024 à maintenant"
      img: /images/photographies_anne-sophie_hovart.png
      githublink: ""
      featuredlink: /images/Photographies_Anne-Sophie_Hovart.pdf
      description: "Voici certaines photographies que j'ai réalisées et retouchées, et que j'aime particulièrement. Logiciels utilisés : Lightroom Classic (retouches) et Photoshop (montages)"

    - name: "Développement et mise en ligne du site de XavPC"
      date: "> Avril-Juillet 2025"
      img: /images/site_xavpc.png
      githublink: ""
      featuredlink: "https://xavpc.fr/"
      description: "Le site étant une vitrine qui ne nécessite pas de mises à jour fréquentes, j'ai choisi de le développer de manière statique, sans CMS ou constructeur, afin de réduire les coûts d'hébergement."
      
    - name: "Refonte du site de XavPC"
      date: "> Avril-Juillet 2025"
      img: /images/refonte_xavpc.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/wDp8OgnjMM8ofTUj5Xm5By/Refonte-site-et-identit%C3%A9-graphique-XavPC?page-id=47%3A27&node-id=189-1156&p=f&viewport=112%2C59%2C0.12&t=pI9qOyHpxySskajI-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=189%3A1156"
      description: "Ayant réalisé mon stage chez XavPC, je me suis penchée sur la refonte de son identité graphique ainsi que sur la refonte de son site que j'avais moi-même réalisé lors de ma première année de DUT informatique, il y a ~4 ans."
    
    - name: "Hugo style Brutalisme"
      date: "> Janvier 2025"
      img: /images/hugo_brutalisme.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/jVMeSTpT0cTEi1m5V9TQkK/Conception-UX---Brutalisme--Memphis?page-id=0%3A1&node-id=152-68&viewport=1795%2C1567%2C0.21&t=sQxOGxjWmT0OVQf9-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=152%3A68&show-proto-sidebar=1"
      description: "Ce projet de cours, où il fallait transformer un site existant dans le style brutalisme (ici, le site du framework gohugo.io m'a permis d'exprimer ma créativité et d'apprendre à créer dans un style qui me plaît très particulièrement."
  
    - name: "Hugo style Memphis"
      date: "> Mars 2025"
      img: /images/hugo_memphis.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/jVMeSTpT0cTEi1m5V9TQkK/Conception-UX---Brutalisme--Memphis?page-id=0%3A1&node-id=570-153&viewport=1795%2C1567%2C0.21&t=sQxOGxjWmT0OVQf9-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=570%3A153&show-proto-sidebar=1"
      description: "Lors d'un projet pour les cours, il fallait transformer un site existant dans le style Memphis. J'ai opté pour le site du framework gohugo.io pour cet exercice, ce qui a constitué un défi très intéressant que j'ai su relever !"
  
    - name: "Refonte du site Croquante"
      date: "> Février - Juillet 2023"
      img: /images/site_croquante.png
      githublink: ""
      featuredlink: "https://xd.adobe.com/view/2a9b257a-f854-4d22-8eb1-355fa922eada-7fc8/"
      description: "Lors de mon alternance, j'ai réalisé les maquettes pour le site de Croquante sous les consignes et conseils d'Anastasia Le Boucher."
    
    - name: "Student Atomicus"
      date: "> Avril 2023"
      img: /images/student_atomicus_hovart_anne-sophie_min.jpg
      featuredlink: /images/student_atomicus_hovart_anne-sophie.jpg
      description: "Pour ce projet photo, il fallait s'inspirer de la photographie surréaliste Dalí Atomicus prie par Philippe Halsman. Cette photo a été prise et retouchée par moi. 🏃‍♂️+📑: Gwenael Mastrilli —— 👟: Tréphine Le Gallic —— 💦: Lucas Girod-Roux"
      
    - name: "UI Challenge"
      date: "> Février 2023"
      img: /images/uichallenge.png
      githublink: ""
      featuredlink: "https://www.figma.com/file/mL4zjnQUlTchybndTvSOuZ/D%C3%A9fis?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: 'Défi 1 : écran de connexion - 45 minutes ——
      Défi 2 : écran de réglage de température - 1h30 ——
      Défi 3 : widget de player de musique - 30 minutes ——
      Défi 4 : écran de choix de pricing - 1h'

    - name: "Application de rencontre pour les +50 ans"
      date: "> Janvier - Février 2023"
      img: /images/maquettes_appli_rencontre.jpg
      githublink: ""
      featuredlink: "https://www.figma.com/file/65W1m0maM6vWf0ADoy7KTi/Appli-rencontre-%2B50-ans-(Copy)?type=design&mode=design&t=bXvvvC08ss68RkEP-1"
      description: "En groupe de trois, nous avons réalisé les maquettes principales d'une application de rencontre pour les + de 50 ans. Nous avons déterminé les leviers et l'objectif. Nous avons étudié les concurrents et avons mis en place un benchmark. Enfin, nous nous sommes penchées sur le parcours utilisateur pour mettre en place l'application."
  
    - name: "Maquettes du site Coatle"
      date: "> Octobre 2022"
      img: /images/coatle.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/TsEP7UFYoXR5UeP1H7zHjf/Exercice-3---Design-Web?page-id=0%3A1&node-id=7-155&starting-point-node-id=7%3A155&scaling=scale-down"
      description: "J'ai réalisé la page d'accueil et la page produit d'un site fictif vendant du chocolat."
      
    - name: "Maquette d'une application de streaming musical"
      date: "> Octobre 2022"
      img: /images/musicapp.png
      githublink: ""
      featuredlink: "https://www.figma.com/proto/eMq1QyXQTC0NUFK5JuD49A/Exercice-2---Design-Web?page-id=0%3A1&node-id=1%3A2&viewport=397%2C167%2C0.04&scaling=scale-down&starting-point-node-id=1%3A2"
      description: "Ceci est la première maquette que je réalise avec Figma. En cliquant sur le lien, vous aurez accès au prototype."

    - name: "Animation d'une image"
      date: "> Septembre 2022"
      img: /images/animation_image.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/X8MwTDyK#D2WaUJAf89PUBIz9AO5-EA666KDSy2vHkKXlqssdVt0"
      description: "Pour ce dernier projet en Motion Design, nous avons dû utiliser tous les outils appris lors des cours."

    - name: "Présentation d'un site web"
      date: "> Septembre 2022"
      img: /images/presentation_site_motion_design.png
      githublink: ""
      featuredlink: "https://mega.nz/file/LoUwFBoY#rn70qMoj3cD__ENj1s7cEFAmDekp69Us_kpLGzBBwH4"
      description: "Pour ce projet en Motion Design, il a fallu assembler dans une composition les captures du site web qu'on souhaitait présenter, et dans une autre, intégrer le défilement. Puis, réaliser l'animation des légendes et le fond."

    - name: "Création d'une bannière web"
      date: "> Septembre 2022"
      img: /images/banniere_web_anim.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/y0tFXDRR#nsmHU66O9H3t1JuXZhiNwhjwFC0n6g4ll_I01wPVlfc"
      description: "Pour ce projet, nous avons dû réaliser une bannière pour une entreprise de notre choix. Il a fallu décomposer la réalisation en deux parties : réaliser d'abord le bandeau des réseaux sociaux puis le reste."

    - name: "Animation d'un logo"
      date: "> Septembre 2022"
      img: /images/anim_logo_iut_lens.jpg
      githublink: ""
      featuredlink: "https://mega.nz/file/qtVAxDbA#clD3AGvOMLXc7CZeSTepo7k44u-YQwPNElKoYz8h3uw"
      description: "En cours de Motion Design, nous avons dû animer le logo de l'IUT de Lens sur After Effects en utilisant différents outils de base pour la prise en main du logiciel."
    
    - name: "Création d'un Burger Quiz en Typescript"
      date: "> Avril 2022"
      img: /images/burgerquiz.PNG
      githublink: ""
      description: "En équipe de 6, nous avons dû réaliser un site internet en Angular, reprenant le concept du Burger Quiz. Pendant deux jours, nous avons travaillé comme si nous étions en entreprise, en suivant la méthode Agile."
      
    - name: "Portfolio"
      date: "> Novembre 2021 -  | Projet pour mes études"
      img: /images/portfo.png
      githublink: "https://github.com/annsopirate/Portfolio"
      featuredlink: "/"
      description: "Création de mon portfolio à l'aide du logiciel Hugo. Grâce à ce projet, j'ai appris à utiliser Hugo correctement et en profondeur !"

    - name: "Projet Web en 48 heures top chrono !"
      date: "> Décembre 2021"
      img: /images/prjtmarathon.png
      githublink: "https://github.com/annsopirate/Projet_Marathon"
      description: "Le \"Projet Marathon\" consistait en la réalisation d'un site de gestion de séries télévisées. Mes deux camarades et moi avons fait équipe avec 3 étudiants en DUT MMI. Nous avons réalisé le back-end et eux le front."

    - name: "Site de l'entreprise XavPC"
      date: "> Été 2021 | Projet personnel"
      img: /images/xavpc.PNG
      featuredlink: "http://xavpc.free.fr/"
      description: "Création de la version 3 du site de l'enteprise XavPC en HTML / CSS. Pour m'entraîner pendant les vacances, j'ai voulu refaire entièrement ce site avec les connaissances acquises en première année."

    - name: "Portail national des IUT informatique"
      date: "> Novembre 2020 - Janvier 2021 | Projet pour mes études"
      img: /images/PNIUTI.PNG
      githublink: "https://github.com/annsopirate/projet_tutore_sem1"
      featuredlink: "https://blurryfoxer.github.io/accueil/accueil.html"
      description: "Nous avons dû, en équipe de trois, refaire le portail national des IUT informatique en HTML / CSS. Ça a été mon projet favori de ma première année."



  # Achievements
  disable_achievements: false
  achievements:
    - title: Projet Voltaire
      description: Obtention du certificat Voltaire avec un total de 848 points.
      img: /images/prjtvol.png
      url: https://mon.certificat-voltaire.fr/verification-certificat?code=AYVGVNV



    - title: CV
      description: Obtenez mon CV.
      img: /images/cv_francais.png
      url: /images/CV_HOVART_Anne-Sophie.pdf

  # Contact
  disable_contact: false
  contact_content: Si vous avez besoin de plus d'informations, ou si mon profil vous correspond, vous pouvez me contacter par mail ! Je me ferai un plaisir d'échanger avec vous.
  email: "annesophie5922@gmail.com"
  
  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false
